prog:Menu.o test.o Player.o Enigme.o BgCam.o Collision.o Jouer.o Input.o EntiteSecondo.o autre.o Multiplayer.o Arduino.o
	gcc Menu.o test.o Player.o Enigme.o BgCam.o Collision.o Jouer.o Input.o EntiteSecondo.o autre.o Multiplayer.o Arduino.o -lm -lSDL -lSDL_image -lSDL_mixer -lSDL_ttf -o prog
test.o:test.c
	gcc -c test.c
Menu.o:Menu.c
	gcc -c Menu.c
Player.o:Player.c
	gcc -c Player.c
Enigme.o:Enigme.c
	gcc -c Enigme.c
BgCam.o:BgCam.c
	gcc -c BgCam.c
Collision.o:Collision.c
	gcc -c Collision.c
Jouer.o:Jouer.c 
	gcc -c Jouer.c
Input.o:Input.c
	gcc -c Input.c
EntiteSecondo.o:EntiteSecondo.c
	gcc -c EntiteSecondo.c
autre.o:autre.c
	gcc -c autre.c
Multiplayer.o:Multiplayer.c
	gcc -c Multiplayer.c
Arduino.o:Arduino.c
	gcc -c Arduino.c
